#!/bin/sh
case $1 in 
      # Install; clones a repo and prints when done; the 2>&1 is so you can pipe it. 
     -i )
        [ -z "$2" ] && printf "No plugin provided\n" && $0 && exit
        git clone --depth 1 --no-single-branch --progress https://github.com/"$2"/"$3" "$HOME"/.vim/pack/plugins/start/"$3" 2>&1 && printf "\033[1m[\033[32;1m*\033[0;1m] Completed installing %s\n\033[0;10m" "$3" && $POSTI ;;
      # Remove; removes the dir, -verbose so there's a completion notice.
     -r )
        [ -z "$2" ] && printf "No plugin provided\n" && $0 && exit
        rm -rfv "$HOME"/.vim/pack/plugins/start/"$2" | sed '$!d;s/directory/plugin/' && $POSTR ;;
      # Update; loops through dirs in ~/.vim/pack/etc.. and runs git pull.
     -u )
        for dir in ~/.vim/pack/plugins/start/*/; do
            cd "$dir" || exit
            printf "\033[1m%s:\\033[0;10m %s\n" "$(pwd | cut -d '/' -f 8)" "$(git pull 2>&1)" && $POSTU ; done ;;
      # List; same as update, gets the author from git remote and last update from last commit in the log.
     -l )
        for dir in ~/.vim/pack/plugins/start/*/; do
            cd "$dir" || exit
            printf "\033[1mPlugin:\\033[34m %s\n\033[0;10m\033[1mAuthor:\\033[31;1;3m %s\n\\033[0;10m\033[1mLast update: \\033[33;1;4m%s\\033[0;10m\n-----------------------\n" "$(pwd | cut -d '/' -f 8)" "$(git config --get remote.origin.url | cut -d "/" -f 4)" "$(git log --pretty=format:'%cr' | head -1)"; done ;;
      # Help
      * )
        printf "\033[1mUsage:\n\n\033[0;10mInstall a plugin: vpkg -i user repo\nRemove a plugin: vpkg -r repo\nUpdate plugins: vpkg -u\nList plugins: vpkg -l\n" ;;
esac
